export const CONFIG_SERVICE = 'CONFIG_SERVICE';
export const LOGGER = 'VX_LOGGER';
export const PLATFORM_PROVIDER = 'PLATFORM_PROVIDER';
export const RESOURCE_EVENT_PROVIDER = 'RESOURCE_EVENT_PROVIDER';
